# Generated by Django 4.2.14 on 2024-08-16 15:47

from django.db import migrations
from ..models import GST

def create(apps, schema_editor):
    GST.objects.create(percent=18)

class Migration(migrations.Migration):

    dependencies = [
        ("revenue", "0003_gst_gst_number"),
    ]

    operations = [migrations.RunPython(create)]
